### ISSUE TITLE
Track date last updated in compound groups

### ISSUE THREAD

**Issue by akokai** [akokai/metacamel#10]
Specify date last updated (CML), in CMG objects and their specifications. Spreadsheet will be trusted source of dates.

**Comment by rashupee** [comment]
Hey Akos,
I'm not sure if this is the right sort of date but it is part of the Compound record. It's called the 'release date' but not sure what that means. cid 2323 is just an example:
```python
s=pcp.Compound.from_cid(2323)
for rec in s.to_dict()['record']['props']:
    print rec['urn']['release']
```
Code returns:
```
2011.04.04
2011.09.13
2011.09.13
2011.09.13
2011.09.13
2011.09.13
2011.09.13
2011.09.13
2011.09.13
2011.09.13
2011.09.13
2011.09.13
2011.09.13
2011.09.13
2011.09.13
2011.09.13
2011.09.13
2011.09.13
2011.09.13
2011.09.13
2011.09.13
```

**Comment by akokai** [comment]
Very cool find. I agree that it's not obvious that what this means. It
would be good to check the (PUG REST API docs)[
https://pubchem.ncbi.nlm.nih.gov/pug_rest/PUG_REST.html] and if still
unclear, to email PubChem support to find out how to get the date a
Compound was created.

On Saturday, June 25, 2016, rashupee <notifications@github.com> wrote:

> Hey Akos,
> I'm not sure if this is the right sort of date but it is part of the
> Compound record. It's called the 'release date' but not sure what that
> means. cid 2323 is just an example:
>
> s=pcp.Compound.from_cid(2323)for rec in s.to_dict()['record']['props']:
>     print rec['urn']['release']
>
> Code returns:
>
> 2011.04.04
> 2011.09.13
> 2011.09.13
> 2011.09.13
> 2011.09.13
> 2011.09.13
> 2011.09.13
> 2011.09.13
> 2011.09.13
> 2011.09.13
> 2011.09.13
> 2011.09.13
> 2011.09.13
> 2011.09.13
> 2011.09.13
> 2011.09.13
> 2011.09.13
> 2011.09.13
> 2011.09.13
> 2011.09.13
> 2011.09.13
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/akokai/metacamel/issues/10#issuecomment-228553097>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABx3pZJo9S3tyTj8N56yuiRB3eWdaoWNks5qPVMxgaJpZM4I-NIv>
> .
>


-- 
Akos Kokai <http://kaios.net/>
PhD candidate, Department of Environmental Science, Policy & Management
<http://ourenvironment.berkeley.edu/>
Fellow, Berkeley Center for Green Chemistry <http://bcgc.berkeley.edu/>
University of California, Berkeley

**Comment by rashupee** [comment]
Hey, so I sent an email asking about the creation date associated with cids. No response yet.

For the same cid as above (2323) I used requests and hit PubChem with its rest client thing-er:
```python
import requests
r = requests.get('http://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/cid/2323/dates/JSON')
r.json()
```
returns
```
{u'InformationList': {u'Information': [{u'CID': 2323,
    u'CreationDate': {u'Day': 25, u'Month': 3, u'Year': 2005}}]}}
```
which is really different from the strange 'release' dates found in the Compound record for the same cid in the previous message:
```
2011.04.04
2011.09.13
```
The puchem docs describe that the above rest-style way of doing things is good for small batches of cids - like 5 per second. It also describes that for cids only the creation date is kept. I don't think they keep track of update or modification dates... but I asked them in my email. We'll see what they say.

**Comment by akokai** [comment]
Confirmed from the API docs [1] that you can use `https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/cid/<CID>/dates/JSON` and get `r.json()['InformationList']['Information']['CreationDate']` to get the date "when a CID first appeared." Yay!

[1] https://pubchem.ncbi.nlm.nih.gov/pug_rest/PUG_REST.html#_Toc409516779
