### ISSUE TITLE
Write a function to query PubChem API for group membership conditions

### ISSUE THREAD

**Issue by akokai** [akokai/metacamel#2]
- Building on what @rashupee has already written using PubChemPy.
- For simplicity, assume that we have CIDs in hand for every compound.
- Also grab the `IUPACName` for each structure.
- We might need several kinds of functions like this later. For now try just making one.

**Comment by rashupee** [comment]
Rad. I'll work on this tomorrow morning first thing.

**Comment by rashupee** [comment]
Hey Akos,

I just pushed code here. Would you let me know what you think when you have a chance? I tried to make complete comments.

The meaty aspect of the code is a function called namesFromCIDSList which takes two arguments: a CMGName string and a cids list. The CMGName string is only used for dictionary key names. The cids list elements are used in pubChemPy API calls. The output is a JSON-style dictionary organization of CMGName,cid value, CASRN, and IUPAC name.

*** I only asked for IUPAC names for cids that had non-empty CASRN matches.

The file writing aspect is there but commented out.

See you laters, Fred

**Comment by akokai** [comment]
This is now taken care of with pull request #9.

We can now do all of the things that your original script does, this time using `CMGroup` objects and the `batch_group_search()` function. However we can now add new functionality and create new ways of automating things, without having to rewrite lots of script code.

The unit tests show how I imagine using these methods. For example, if you run `py.test -v` and look in the `results` directory there should be a few Excel files showing examples of exported compound groups (but with only 3 compounds per group, just to save time on running the test). FYI All of the log messages now show up in `log/metacamel.log` and on the console, but py.test suppresses them on the console.

I have not yet written an actual script that goes and does a *full* search on a full set of groups, etc.... the tests are sufficient for now. But that is the end goal!
